sudo: false
language: erlang
otp_release:
  - 23.3.1
  - 24.3.1
  - 25.1.1
env: MAKE_TARGET=ci
before_script:
  - hostname -f
  - cc -v
  - ld -v
  - find .rebar
after_script:
  - find .rebar
matrix:
  include:
    - otp_release: 25.1.1
      env: MAKE_TARGET=ci-dialyze
  allow_failures:
    - otp_release: 25.1.1
      env: MAKE_TARGET=ci-dialyze
script: make $MAKE_TARGET
cache:
  directories:
    - .rebar
before_cache:
  - rm -fv .rebar/erlcinfo
  - rm -fv $HOME/.cache/.rebar/erlcinfo
